curriculum.pdf: cg.png Convergence_error_stdev.pdf crash.jpg cuda.png curriculum.tex dd.png \
		FivePointStencil.pdf njord_1.jpg open-mpi-logo.png openmp.png serial.pdf
	pdflatex -output-directory ../tmp curriculum.tex
	mv ../tmp/curriculum.pdf ..
