mpi.pdf: Allreduce.pdf GlobalLocalMapping.pdf message_passing_model.pdf Midpoint.pdf \
	 mpi_op1.pdf mpi_op2.pdf mpi.tex pi_sp_new.pdf Vector1.pdf Vector2.pdf Vector3.pdf
	pdflatex -output-directory ../tmp mpi.tex
	mv ../tmp/mpi.pdf ..
