single.pdf: AdjacentMemory.pdf CacheTrashing.pdf DirectMappedCache.pdf Lande.pdf \
 	    MemoryHierarchy.pdf NWayCache.pdf single.tex SuperScalar.pdf
	pdflatex -output-directory ../tmp single.tex
	pdflatex -output-directory ../tmp single.tex
	mv ../tmp/single.pdf ..
