summing.pdf: blas-mxv.c mpi-mxv.c openmp-mxv.c openmp-mxv-ref.c serial-mxv-2.c \
             serial-mxv.c serial-mxv-ref.c summing.tex

	     pdflatex -output-directory ../tmp summing.tex
	     pdflatex -output-directory ../tmp summing.tex
	     mv ../tmp/summing.pdf ..
