trends.pdf: climate_model.jpg met.png njord_1.jpg njord_2.jpg njord_john.jpg \
		Performance_Development.png Projected_Performance_Development.png simra.png trends.tex
	pdflatex -output-directory ../tmp trends.tex
	mv ../tmp/trends.pdf ..
