poisson-solvers.pdf: poisson-solvers.tex prototype.c solve-lu.c
	pdflatex -output-directory ../tmp poisson-solvers.tex
	pdflatex -output-directory ../tmp poisson-solvers.tex
	mv ../tmp/poisson-solvers.pdf ..
