#!/bin/bash

#PBS -N test
#PBS -lnodes=4:ppn=12:default
#PBS -lwalltime=12:00:00
#PBS -lpmem=2000MB
#PBS -A freecycle
#PBS -q optimist
#PBS -j oe

cd ${PBS_O_WORKDIR}

module load intelcomp
module load openmpi/1.4.3-intel
KMP_AFFINITY="granularity=fine,compact"
OMP_NUM_THREADS=3 mpirun -npernode 12 myjob myparams
