thetool.pdf: thetool.tex wrong-tool-pizza.jpg ../../notes/01.single/Lande.pdf \
             ../../notes/01.single/MemoryHierarchy.pdf \
	     ../../notes/00.intro/ieee.pdf \
             ../../notes/01.single/SuperScalar.pdf \
	     ../../notes/01.single/DirectMappedCache.pdf \
	     ../../notes/01.single/CacheTrashing.pdf \
	     ../../notes/01.single/AdjacentMemory.pdf \
	     ../../notes/01.single/NWayCache.pdf
	pdflatex -output-directory ../tmp thetool.tex
	mv ../tmp/thetool.pdf ..
