poisson-slides.pdf: poisson-slides.tex conv1.m poisson1D.m source1.m exact1.m
	pdflatex -output-directory ../tmp poisson-slides.tex
	pdflatex -output-directory ../tmp poisson-slides.tex
	mv ../tmp/poisson-slides.pdf ..
