intro.pdf: climate_model.jpg figure1.png ieee.pdf intro.tex met.png njord_1.jpg njord_2.jpg \
  	   njord_john.jpg Performance_Development.png Projected_Performance_Development.png
	pdflatex -output-directory ../tmp intro.tex
	mv ../tmp/intro.pdf ..
